{{- if .Values.components.webhook.enabled }}
apiVersion: {{ include "deployment.apiVersion" . }}
kind: Deployment
metadata:
  labels:
    app: horusec-webhook
  name: {{ .Values.components.webhook.name }}
  namespace: {{ .Release.Namespace }}
spec:
  {{- if not .Values.components.webhook.pod.autoscaling.enabled }}
  replicas: {{ .Values.components.webhook.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      app: horusec-webhook
  template:
    metadata:
      labels:
        app: horusec-webhook
    spec:
      {{- include "webhook.imagePullSecrets" . | nindent 6 -}}
      containers:
        - env:
            - name: HORUSEC_PORT
              value: {{ .Values.components.webhook.port.http | quote }}
            - name: HORUSEC_SWAGGER_HOST
              value: 0.0.0.0
            - name: HORUSEC_BROKER_HOST
              value: {{ .Values.global.broker.host }}
            - name: HORUSEC_BROKER_PORT
              value: {{ .Values.global.broker.port | quote }}
            - name: HORUSEC_DATABASE_SQL_LOG_MODE
              value: {{ .Values.global.database.logMode | quote }}
            - name: HORUSEC_DATABASE_SQL_DIALECT
              value: {{ .Values.global.database.dialect }}
            - name: HORUSEC_BROKER_USERNAME
              valueFrom:
                secretKeyRef:
                  key: username
                  name: {{ .Values.global.broker.secretName }}
            - name: HORUSEC_BROKER_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: {{ .Values.global.broker.secretName }}
            - name: HORUSEC_DATABASE_USERNAME
              valueFrom:
                secretKeyRef:
                  key: username
                  name: {{ .Values.global.database.secretName }}
            - name: HORUSEC_DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: {{ .Values.global.database.secretName }}
            - name: HORUSEC_DATABASE_SQL_URI
              value: "postgresql://$(HORUSEC_DATABASE_USERNAME):$(HORUSEC_DATABASE_PASSWORD)@{{- .Values.global.database.host -}}:{{- .Values.global.database.port -}}/{{- .Values.global.database.name -}}{{- if not .Values.global.database.sslMode -}}?sslmode=disable{{- end -}}"
            - name: HORUSEC_JWT_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  key: secret-key
                  name: {{ .Values.global.jwt.secretName }}
            {{- if .Values.components.webhook.extraEnv }}
            # Extra environment variables
            {{- toYaml .Values.components.webhook.extraEnv | nindent 12 }}
            {{- end }}
          image: "{{ template "webhook.image" . }}"
          imagePullPolicy: {{ .Values.components.webhook.container.image.pullPolicy | quote }}
          name: horusec-webhook
          ports:
          {{- range $key, $value := .Values.components.webhook.port }}
            - containerPort: {{ $value }}
              name: {{ $key }}
              protocol: TCP
          {{- end }}
          livenessProbe:
            httpGet:
              path: /webhook/health
              port: {{ .Values.components.webhook.port.http }}
              scheme: HTTP
            initialDelaySeconds: 3
            periodSeconds: 3
          readinessProbe:
            httpGet:
              path: /webhook/health
              port: {{ .Values.components.webhook.port.http }}
              scheme: HTTP
            initialDelaySeconds: 3
            periodSeconds: 3
          resources: {{- toYaml .Values.components.webhook.container.resources | nindent 12 }}
          {{- if .Values.components.webhook.container.securityContext.enabled }}
          securityContext: {{- omit .Values.components.webhook.container.securityContext "enabled" | toYaml | nindent 12 }}
          {{- end }}
      {{- if .Values.components.webhook.pod.securityContext.enabled }}
      securityContext: {{- omit .Values.components.webhook.pod.securityContext "enabled" | toYaml | nindent 8 }}
      {{- end }}
      serviceAccountName: webhook
      terminationGracePeriodSeconds: 30
{{- end }}