profile: demo

global:
  common:
    pod:
      autoscaling:
        enabled: false
        minReplicas: 1
        maxReplicas: 11
        # targetCPU: 50
        # targetMemory: 50
      securityContext:
        enabled: false
        fsGroup: 1001

    container:
      image:
        registry: docker.io
        pullPolicy: IfNotPresent
        pullSecrets: [ ]
      securityContext:
        enabled: false
        runAsUser: 1001

  administrator:
    enabled: false
    username: ""
    email: ""
    password: ""

  jwt:
    secretName: "horusec-jwt"

  broker:
    enabled: true
    host: "rabbitmq.queue"
    port: 5672
    secretName: "horusec-broker"

  database:
    name: "horusec_db"
    host: "postgresql.database"
    port: 5432
    dialect: "postgres"
    sslMode: false
    logMode: false
    secretName: "horusec-database"

  keycloak:
    publicURL: https://keycloak.local/auth
    internalURL: "" # This field is optional. If not filled, the publicURL will be used.
    realm: zup
    otp: false
    clients:
      public:
        id: manager
      confidential:
        id: auth
        secret: c4f2f7b1-478b-4b52-9758-c272b936da8c

  mailServer:
    host: "smtp.mailtrap.io"
    port: 25
    secretName: "horusec-smtp"

components:
  account:
    name: account
    enabled: true
    port:
      http: 8003
    ingress:
      enabled: true
      scheme: "http"
      host: "account.local"
      path: /account
      protocols:
        - http
    extraEnv: []
    replicaCount: 1
    pod:
      autoscaling:
        enabled: false
        minReplicas: 1
        maxReplicas: 11
        # targetCPU: 50
        # targetMemory: 50
      securityContext:
        enabled: false
        fsGroup: 1001
    container:
      image:
        registry: docker.io
        repository: horuszup/horusec-account
        tag: v1.2.1
        pullPolicy: IfNotPresent
        pullSecrets: [ ]
      securityContext:
        enabled: false
        runAsUser: 1001
      resources:
        limits: {}
        #   cpu: 500m
        #   memory: 1Gi
        requests: {}
        #   cpu: 300m
        #   memory: 512Mi

  analytic:
    name: analytic
    enabled: true
    port:
      http: 8005
    ingress:
      enabled: true
      scheme: "http"
      host: "analytic.local"
      path: /analytic
      protocols:
        - http
    extraEnv: []
    replicaCount: 1
    pod:
      autoscaling:
        enabled: false
        minReplicas: 1
        maxReplicas: 11
        # targetCPU: 50
        # targetMemory: 50
      securityContext:
        enabled: false
        fsGroup: 1001
    container:
      image:
        registry: docker.io
        repository: horuszup/horusec-analytic
        tag: v1.2.1
        pullPolicy: IfNotPresent
        pullSecrets: [ ]
      securityContext:
        enabled: false
        runAsUser: 1001
      resources:
        limits: {}
        #   cpu: 500m
        #   memory: 1Gi
        requests: {}
        #   cpu: 300m
        #   memory: 512Mi

  api:
    name: api
    enabled: true
    port:
      http: 8000
    ingress:
      enabled: true
      scheme: "http"
      host: "api.local"
      path: /api
      protocols:
        - http
    extraEnv: []
    replicaCount: 1
    pod:
      autoscaling:
        enabled: false
        minReplicas: 1
        maxReplicas: 11
        # targetCPU: 50
        # targetMemory: 50
      securityContext:
        enabled: false
        fsGroup: 1001
    container:
      image:
        registry: docker.io
        repository: horuszup/horusec-api
        tag: v2.10.1
        pullPolicy: IfNotPresent
        pullSecrets: [ ]
      securityContext:
        enabled: false
        runAsUser: 1001
      resources:
        limits: {}
        #   cpu: 500m
        #   memory: 1Gi
        requests: {}
        #   cpu: 300m
        #   memory: 512Mi

  auth:
    name: auth
    type: horusec
    enabled: true
    port:
      http: 8006
      grpc: 8007
    ingress:
      enabled: true
      scheme: "http"
      host: "auth.local"
      path: /auth
      protocols:
        - http
    extraEnv: []
    replicaCount: 1
    pod:
      autoscaling:
        enabled: false
        minReplicas: 1
        maxReplicas: 11
        # targetCPU: 50
        # targetMemory: 50
      securityContext:
        enabled: false
        fsGroup: 1001
    container:
      image:
        registry: docker.io
        repository: horuszup/horusec-auth
        tag: v1.7.1
        pullPolicy: IfNotPresent
        pullSecrets: [ ]
      securityContext:
        enabled: false
        runAsUser: 1001
      resources:
        limits: {}
        #   cpu: 500m
        #   memory: 1Gi
        requests: {}
        #   cpu: 300m
        #   memory: 512Mi

  manager:
    name: manager
    enabled: true
    port:
      http: 8080
    ingress:
      enabled: true
      scheme: "http"
      host: "manager.local"
      path: /horusec
      protocols:
        - http
    extraEnv: []
    replicaCount: 1
    pod:
      autoscaling:
        enabled: false
        minReplicas: 1
        maxReplicas: 11
        # targetCPU: 50
        # targetMemory: 50
      securityContext:
        enabled: false
        fsGroup: 1001
    container:
      image:
        registry: docker.io
        repository: horuszup/horusec-manager
        tag: v1.9.0
        pullPolicy: IfNotPresent
        pullSecrets: [ ]
      securityContext:
        enabled: false
        runAsUser: 1001
      resources:
        limits: {}
        #   cpu: 500m
        #   memory: 1Gi
        requests: {}
        #   cpu: 300m
        #   memory: 512Mi

  webhook:
    name: webhook
    enabled: true
    port:
      http: 8005
    extraEnv: []
    replicaCount: 1
    pod:
      autoscaling:
        enabled: false
        minReplicas: 1
        maxReplicas: 11
        # targetCPU: 50
        # targetMemory: 50
      securityContext:
        enabled: false
        fsGroup: 1001
    container:
      image:
        registry: docker.io
        repository: horuszup/horusec-webhook
        tag: v1.2.1
        pullPolicy: IfNotPresent
        pullSecrets: [ ]
      securityContext:
        enabled: false
        runAsUser: 1001
      resources:
        limits: {}
        #   cpu: 500m
        #   memory: 1Gi
        requests: {}
        #   cpu: 300m
        #   memory: 512Mi

  messages:
    name: messages
    enabled: true
    port:
      http: 8004
    extraEnv: []
    replicaCount: 1
    pod:
      autoscaling:
        enabled: false
        minReplicas: 1
        maxReplicas: 11
        # targetCPU: 50
        # targetMemory: 50
      securityContext:
        enabled: false
        fsGroup: 1001
    container:
      image:
        registry: docker.io
        repository: horuszup/horusec-messages
        tag: v1.8.1
        pullPolicy: IfNotPresent
        pullSecrets: [ ]
      securityContext:
        enabled: false
        runAsUser: 1001
      resources:
        limits: {}
        #   cpu: 500m
        #   memory: 1Gi
        requests: {}
        #   cpu: 300m
        #   memory: 512Mi
