# Copyright 2021 ZUP IT SERVICOS EM TECNOLOGIA E INOVACAO SA
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

---
apiVersion: install.horusec.io/v2alpha1
kind: HorusecPlatform
metadata:
  name: horusecplatform-sample
spec:
  components:
    analytic:
      database:
        host: ""
        name: horusec_analytic_db
        password:
          secretKeyRef:
            key: password
            name: horusec-analytic-database
        user:
          secretKeyRef:
            key: username
            name: horusec-analytic-database
      ingress:
        host: manager.horus.dev.zup.corp
        tls:
          secretName: horusec-tls
    api:
      ingress:
        host: manager.horus.dev.zup.corp
        tls:
          secretName: horusec-tls
    auth:
      ingress:
        host: manager.horus.dev.zup.corp
        tls:
          secretName: horusec-tls
    core:
      ingress:
        host: manager.horus.dev.zup.corp
        tls:
          secretName: horusec-tls
    manager:
      ingress:
        host: manager.horus.dev.zup.corp
        tls:
          secretName: horusec-tls
    messages:
      container:
        livenessProbe:
          timeoutSeconds: 3
        readinessProbe:
          timeoutSeconds: 3
      ingress:
        host: manager.horus.dev.zup.corp
        tls:
          secretName: horusec-tls
      mailServer:
        host: smtp.mailtrap.io
        password:
          secretKeyRef:
            key: password
            name: horusec-smtp
        user:
          secretKeyRef:
            key: username
            name: horusec-smtp
    vulnerability:
      ingress:
        host: manager.horus.dev.zup.corp
        tls:
          secretName: horusec-tls
    webhook:
      ingress:
        host: manager.horus.dev.zup.corp
        tls:
          secretName: horusec-tls
  global:
    broker:
      host: rabbitmq
      password:
        secretKeyRef:
          key: password
          name: horusec-broker
      user:
        secretKeyRef:
          key: username
          name: horusec-broker
    database:
      host: ""
      name: horusec_db
      password:
        secretKeyRef:
          key: password
          name: horusec-platform-database
      user:
        secretKeyRef:
          key: username
          name: horusec-platform-database
