apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-migration
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-1"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    metadata:
      name: migration
    spec:
      restartPolicy: Never
      containers:
        - name: horusec-database-migration
          image: "horuszup/horusec-migration:latest"
          command: [ "migrate.sh" ]
          env:
            - name: HORUSEC_DATABASE_USERNAME
              valueFrom:
                secretKeyRef:
                  key: username
                  name: {{ .Values.global.database.secretName }}
            - name: HORUSEC_DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: {{ .Values.global.database.secretName }}
            - name: HORUSEC_DATABASE_SQL_URI
              value: "postgresql://$(HORUSEC_DATABASE_USERNAME):$(HORUSEC_DATABASE_PASSWORD)@{{- .Values.global.database.host -}}:{{- .Values.global.database.port -}}/{{- .Values.global.database.name -}}{{- if not .Values.global.database.sslMode -}}?sslmode=disable{{- end -}}"
